# Generated by Django 4.1.2 on 2022-12-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.CharField(blank='True', max_length=50, null='True', unique='False'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank='True', max_length=200, null='True', unique='False'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank='True', max_length=20, null='True', unique='False'),
            preserve_default='True',
        ),
    ]
