version: "3.8"
services:
  db:
    image: postgres:13-alpine  # use the latest postgres image
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"  # map port 8000 on host to port 8000 in container
    container_name: postgres_db
  app:
    build: .  # build from Dockerfile in current directory
    volumes:
      - ./:/app  #
    restart: always
    ports:
      - "8000:8000"  # map port 8000 on host to port 8000 in container
    image: app:latest  # tag the image as app:latest
    container_name: swe573_term_project  # name the container as swe573_term_project
    command: >
      sh -c "sleep 5 &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db  # start the db container before starting the app container
